sudo: required

dist: xenial

language: python

python:
 - '3.7'

install:
 - pip install -r requirements.txt

script:
 - coverage run --branch --source . -m pytest

after_success:
  - coverage report
  - coveralls
